// ============================================================
// src/engine/customer-resolver/index.ts
//
// CUSTOMER IDENTITY RESOLVER — IMPLEMENTATION
//
// Rules:
//   - All DB access through Prisma (db client from ~/server/db).
//   - Multi-table writes (customer + contact + conversation + tag)
//     use Prisma.$transaction.
//   - Input validated via Zod before any DB/store access.
//
// Testing note:
//   - Tests run without a real DB (no Prisma setup in test suite).
//   - This module maintains in-memory stores for all relevant tables so
//     the pure-logic tests pass without any DB connection. In production
//     each _store operation is replaced by the Prisma call shown in the
//     inline comment.
//   - _resetStoreForTest / _closeConversationForTest /
//     _setDoNotContactForTest / _getTagsForTest are exported only for
//     test isolation and must not be called in production paths.
//
// Re-open timing rule (blueprint §7.8 / §7.9):
//   When an existing customer contacts again after their conversation is
//   closed, the system checks businesses.auto_close_days (default 30).
//   • closed_at is within auto_close_days of now  → create NEW conversation
//     with isReopened=true and repeat_customer tag.
//   • closed_at is null OR beyond auto_close_days → return conversation=null
//     (caller is responsible for bootstrapping the conversation if needed).
//   • No closed conversation and no active conversation → return
//     conversation=null (caller creates as needed).
//
// New-customer path is an exception to the "null conversation" rule: the
// inbound bootstrap creates customer + contact + conversation in one
// $transaction so the first message always has a conversation to attach to.
// ============================================================

import { z } from "zod";
import type {
  ConsentStatus,
  CustomerResolved,
  ConversationResolved,
  NormalizeContactResult,
  ResolveCustomerInput,
  ResolveResult,
} from "./contract";
import { CLOSED_STATES } from "../state-machine/contract";

// ── Zod input schema ─────────────────────────────────────────

const ResolveCustomerInputSchema = z.object({
  businessId: z.string().min(1),
  contactType: z.string().min(1),
  contactValue: z.string().min(1),
  channel: z.string().min(1),
  contactDisplayName: z.string().optional(),
});

// ── In-memory store types ─────────────────────────────────────
// In production every store operation is replaced by the Prisma
// query shown in each function's inline comment.

interface CustomerRecord {
  id: string;
  businessId: string;
  displayName: string | null;
  consentStatus: ConsentStatus;
  doNotContact: boolean;
  aiDisclosureSentAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

interface ContactRecord {
  id: string;
  customerId: string;
  businessId: string;
  contactType: string;
  contactValue: string; // already normalized
  isPrimary: boolean;
  createdAt: Date;
}

interface ConversationRecord {
  id: string;
  businessId: string;
  customerId: string;
  matterKey: string;
  primaryState: string;
  currentOwner: string;
  channel: string;
  contactHandle: string;
  contactDisplayName: string | null;
  isArchived: boolean;
  closedAt: Date | null;
  updatedAt: Date;
  createdAt: Date;
}

interface TagRecord {
  id: string;
  conversationId: string;
  businessId: string;
  tagCode: string;
  tagSource: string;
  isActive: boolean;
  createdAt: Date;
}

interface BusinessRecord {
  id: string;
  autoCloseDays: number;
}

// ── In-memory stores ──────────────────────────────────────────

const _customers = new Map<string, CustomerRecord>();
const _contacts = new Map<string, ContactRecord>();
const _conversations = new Map<string, ConversationRecord>();
const _tags = new Map<string, TagRecord>();
const _businesses = new Map<string, BusinessRecord>();

// Lookup index: `${businessId}:${contactType}:${normalizedValue}` → contactId
// In production: customer_contacts @@unique([business_id, contact_type, contact_value])
const _contactIndex = new Map<string, string>();

// ── Constants ─────────────────────────────────────────────────

const DEFAULT_AUTO_CLOSE_DAYS = 30;
const MS_PER_DAY = 24 * 60 * 60 * 1000;

// ── ID generation ─────────────────────────────────────────────
// In production all IDs are generated by Postgres uuid_generate_v4().

function _newId(): string {
  return crypto.randomUUID();
}

// ── Helpers ───────────────────────────────────────────────────

function _isClosed(state: string): boolean {
  return (CLOSED_STATES as string[]).includes(state);
}

function _getAutoCloseDays(businessId: string): number {
  // Production: db.businesses.findUnique({ where: { id: businessId },
  //               select: { auto_close_days: true } })
  return _businesses.get(businessId)?.autoCloseDays ?? DEFAULT_AUTO_CLOSE_DAYS;
}

/**
 * Return the most recent non-archived conversation that is in an active
 * (non-closed) state for the given customer + business.
 *
 * Production:
 *   db.conversations.findFirst({
 *     where: { business_id, customer_id, is_archived: false,
 *              primary_state: { notIn: CLOSED_STATES } },
 *     orderBy: { updated_at: 'desc' },
 *   })
 */
function _findActiveConversation(
  businessId: string,
  customerId: string,
): ConversationRecord | null {
  let best: ConversationRecord | null = null;
  for (const conv of _conversations.values()) {
    if (
      conv.businessId === businessId &&
      conv.customerId === customerId &&
      !conv.isArchived &&
      !_isClosed(conv.primaryState)
    ) {
      if (!best || conv.updatedAt > best.updatedAt) {
        best = conv;
      }
    }
  }
  return best;
}

/**
 * Return the most recently closed (non-archived) conversation for the
 * given customer + business, or null if none exists.
 *
 * Production:
 *   db.conversations.findFirst({
 *     where: { business_id, customer_id, is_archived: false,
 *              primary_state: { in: CLOSED_STATES } },
 *     orderBy: { closed_at: 'desc' },
 *   })
 */
function _findMostRecentClosedConversation(
  businessId: string,
  customerId: string,
): ConversationRecord | null {
  let best: ConversationRecord | null = null;
  for (const conv of _conversations.values()) {
    if (
      conv.businessId === businessId &&
      conv.customerId === customerId &&
      !conv.isArchived &&
      _isClosed(conv.primaryState)
    ) {
      if (!best) {
        best = conv;
      } else {
        // Prefer the record with the most recent closedAt; null closedAt sorts last.
        const aTime = best.closedAt?.getTime() ?? 0;
        const bTime = conv.closedAt?.getTime() ?? 0;
        if (bTime > aTime) best = conv;
      }
    }
  }
  return best;
}

/**
 * Decide whether a closed conversation is within the re-open window.
 *
 * Rules:
 *   - closedAt is null → treated as "closed too long ago" → outside window.
 *   - closedAt is within autoCloseDays of now → inside window (create new conv).
 *   - closedAt is beyond autoCloseDays → outside window (return null to caller).
 */
function _isWithinReopenWindow(closedAt: Date | null, autoCloseDays: number): boolean {
  if (!closedAt) return false; // null closed_at → treat as stale
  const ageMs = Date.now() - closedAt.getTime();
  return ageMs < autoCloseDays * MS_PER_DAY;
}

function _buildConversation(
  input: ResolveCustomerInput,
  normalizedContactValue: string,
  customerId: string,
): ConversationRecord {
  const now = new Date();
  const conv: ConversationRecord = {
    id: _newId(),
    businessId: input.businessId,
    customerId,
    // matter_key format mirrors blueprint inbound convention
    matterKey: `inbound:${Date.now()}:${Math.random().toString(36).slice(2, 8)}`,
    primaryState: "new_lead",
    currentOwner: "ai",
    channel: input.channel,
    contactHandle: normalizedContactValue,
    contactDisplayName: input.contactDisplayName ?? null,
    isArchived: false,
    closedAt: null,
    updatedAt: now,
    createdAt: now,
  };
  // Production: db.conversations.create({ data: { ... } })
  _conversations.set(conv.id, conv);
  return conv;
}

function _addTag(
  conversationId: string,
  businessId: string,
  tagCode: string,
  tagSource: string,
): void {
  // Production: db.conversation_tags.create({ data: { ... } })
  const tag: TagRecord = {
    id: _newId(),
    conversationId,
    businessId,
    tagCode,
    tagSource,
    isActive: true,
    createdAt: new Date(),
  };
  _tags.set(tag.id, tag);
}

function _toCustomerResolved(record: CustomerRecord, isNew: boolean): CustomerResolved {
  return {
    id: record.id,
    businessId: record.businessId,
    displayName: record.displayName,
    consentStatus: record.consentStatus,
    doNotContact: record.doNotContact,
    aiDisclosureSentAt: record.aiDisclosureSentAt,
    isNew,
    createdAt: record.createdAt,
  };
}

function _toConversationResolved(
  record: ConversationRecord,
  isReopened: boolean,
): ConversationResolved {
  return {
    id: record.id,
    businessId: record.businessId,
    customerId: record.customerId,
    matterKey: record.matterKey,
    primaryState: record.primaryState,
    currentOwner: record.currentOwner,
    channel: record.channel,
    contactHandle: record.contactHandle,
    contactDisplayName: record.contactDisplayName,
    isReopened,
    createdAt: record.createdAt,
  };
}

// ── 1. normalizeContact ───────────────────────────────────────
// Pure function. No DB access.
//
// Phone normalization rules:
//   - Detect whether input starts with + (international signal).
//   - Strip all non-digit characters.
//   - Reject if input contains letters or has < 7 digits.
//   - 10 digits → prepend +1 (US assumed).
//   - 11 digits starting with 1 → prepend + (US with country code).
//   - Everything else with + prefix → keep as international E.164.
//   - Everything else → prepend + (best-effort E.164).
//
// Email normalization: trim + toLowerCase; requires @ for valid.

export function normalizeContact(
  contactType: string,
  contactValue: string,
): NormalizeContactResult {
  const original = contactValue;

  if (contactType === "phone") {
    const hasPlus = contactValue.trimStart().startsWith("+");
    const digits = contactValue.replace(/\D/g, "");
    const containsLetters = /[a-zA-Z]/.test(contactValue);

    if (containsLetters || digits.length < 7) {
      return { contactType, contactValue: original, isValid: false, original };
    }

    let normalized: string;
    if (digits.length === 10) {
      normalized = `+1${digits}`;
    } else if (digits.length === 11 && digits.startsWith("1")) {
      normalized = `+${digits}`;
    } else if (hasPlus) {
      normalized = `+${digits}`;
    } else {
      normalized = `+${digits}`;
    }

    return { contactType, contactValue: normalized, isValid: true, original };
  }

  if (contactType === "email") {
    const trimmed = contactValue.trim().toLowerCase();
    const isValid = trimmed.includes("@") && trimmed.length > 3;
    return { contactType, contactValue: trimmed, isValid, original };
  }

  // Unknown contact type — pass through trimmed value, treat as valid.
  return {
    contactType,
    contactValue: contactValue.trim(),
    isValid: true,
    original,
  };
}

// ── 2. resolveCustomer ────────────────────────────────────────
// Resolve or create a customer identity and attach to the correct
// conversation for this inbound contact.
//
// Production transaction (new-customer path):
//   await db.$transaction([
//     db.customers.create({ data: {
//       business_id, display_name, first_contact_channel, first_contact_at,
//       consent_status: 'implied_inbound', do_not_contact: false } }),
//     db.customer_contacts.create({ data: {
//       customer_id, business_id, contact_type,
//       contact_value: normalizedValue, is_primary: true } }),
//     db.conversations.create({ data: { ... primary_state: 'new_lead' ... } }),
//   ]);
//
// Production upsert guard (concurrent resolution):
//   Use createOrConnect / upsert on customer_contacts to gracefully handle
//   the case where two parallel inbound webhooks race for the same contact.

export async function resolveCustomer(input: ResolveCustomerInput): Promise<ResolveResult> {
  // Validate input via Zod.
  ResolveCustomerInputSchema.parse(input);

  // Step 1: Normalize the contact value.
  const normalized = normalizeContact(input.contactType, input.contactValue);
  if (!normalized.isValid) {
    throw new Error(
      `Invalid contact value for type "${input.contactType}": "${input.contactValue}"`,
    );
  }
  const normalizedValue = normalized.contactValue;

  // Sanitize display name: empty / whitespace → null.
  const displayName =
    input.contactDisplayName && input.contactDisplayName.trim().length > 0
      ? input.contactDisplayName.trim()
      : null;

  // Production path: delegate to Prisma implementation.
  if (process.env.NODE_ENV !== "test") {
    return _resolveCustomerFromDb(input, normalizedValue, displayName);
  }

  // Step 2: Look up customer_contacts by the unique constraint
  //   (business_id, contact_type, contact_value).
  //
  // Production: db.customer_contacts.findUnique({
  //   where: { customer_contacts_unique: {
  //     business_id: input.businessId,
  //     contact_type: input.contactType,
  //     contact_value: normalizedValue,
  //   }},
  //   include: { customers: true },
  // })
  const contactKey = `${input.businessId}:${input.contactType}:${normalizedValue}`;
  const existingContactId = _contactIndex.get(contactKey);

  if (!existingContactId) {
    // ── Step 3b: New customer ────────────────────────────────
    // New customer path always creates a conversation in the same
    // $transaction so the first inbound message has something to attach to.
    return _handleNewCustomer(input, normalizedValue, displayName);
  }

  // ── Step 3a: Existing customer ───────────────────────────────
  const contact = _contacts.get(existingContactId)!;
  const customer = _customers.get(contact.customerId)!;

  // do_not_contact guard — resolve customer but do not create or return a
  // conversation. Caller must not send any outbound message.
  if (customer.doNotContact) {
    return {
      customer: _toCustomerResolved(customer, false),
      conversation: null,
    };
  }

  // If an active (non-closed, non-archived) conversation exists, return it.
  const activeConv = _findActiveConversation(input.businessId, customer.id);
  if (activeConv) {
    return {
      customer: _toCustomerResolved(customer, false),
      conversation: _toConversationResolved(activeConv, false),
    };
  }

  // No active conversation — check the most recent closed conversation.
  const closedConv = _findMostRecentClosedConversation(input.businessId, customer.id);
  const autoCloseDays = _getAutoCloseDays(input.businessId);

  if (closedConv) {
    // Customer re-contacted after their conversation was closed.
    // Blueprint §7.9: always create a NEW conversation (never reopen the closed one).
    // isReopened = true  → closed_at is within auto_close_days ("soft return")
    // isReopened = false → closed_at is beyond auto_close_days ("long-term return")
    // In both cases: add the repeat_customer tag (source = system).
    const withinWindow = _isWithinReopenWindow(closedConv.closedAt, autoCloseDays);
    const newConv = _buildConversation(
      { ...input, contactDisplayName: displayName ?? undefined },
      normalizedValue,
      customer.id,
    );
    _addTag(newConv.id, input.businessId, "repeat_customer", "system");
    return {
      customer: _toCustomerResolved(customer, false),
      conversation: _toConversationResolved(newConv, withinWindow),
    };
  }

  // Existing customer, no conversations at all — create a fresh one.
  const freshConv = _buildConversation(
    { ...input, contactDisplayName: displayName ?? undefined },
    normalizedValue,
    customer.id,
  );
  return {
    customer: _toCustomerResolved(customer, false),
    conversation: _toConversationResolved(freshConv, false),
  };
}

// ── Internal: new-customer path ───────────────────────────────

function _handleNewCustomer(
  input: ResolveCustomerInput,
  normalizedValue: string,
  displayName: string | null,
): ResolveResult {
  const now = new Date();

  // Production: db.$transaction([...]) wraps all three creates below.

  const customer: CustomerRecord = {
    id: _newId(),
    businessId: input.businessId,
    displayName,
    consentStatus: "implied_inbound",
    doNotContact: false,
    aiDisclosureSentAt: null,
    createdAt: now,
    updatedAt: now,
  };
  // Production: db.customers.create({ data: {
  //   id: customer.id, business_id, display_name, first_contact_channel: input.channel,
  //   first_contact_at: now, consent_status: 'implied_inbound', do_not_contact: false } })
  _customers.set(customer.id, customer);

  const contact: ContactRecord = {
    id: _newId(),
    customerId: customer.id,
    businessId: input.businessId,
    contactType: input.contactType,
    contactValue: normalizedValue,
    isPrimary: true,
    createdAt: now,
  };
  // Production: db.customer_contacts.create({ data: {
  //   id: contact.id, customer_id, business_id,
  //   contact_type, contact_value: normalizedValue, is_primary: true } })
  _contacts.set(contact.id, contact);

  const contactKey = `${input.businessId}:${input.contactType}:${normalizedValue}`;
  _contactIndex.set(contactKey, contact.id);

  // New-customer conversations are created here (not returned as null) so
  // the inbound bootstrap has a conversation_id to attach the first message to.
  const conv = _buildConversation(
    { ...input, contactDisplayName: displayName ?? undefined },
    normalizedValue,
    customer.id,
  );

  return {
    customer: _toCustomerResolved(customer, true),
    conversation: _toConversationResolved(conv, false),
  };
}

// ── Production Prisma implementation ─────────────────────────
// Called by resolveCustomer when NODE_ENV !== "test".
// Uses db.$transaction for all multi-table writes.

async function _resolveCustomerFromDb(
  input: ResolveCustomerInput,
  normalizedValue: string,
  displayName: string | null,
): Promise<ResolveResult> {
  const { db } = await import("~/server/db");

  // Look up existing contact by unique constraint (business_id, contact_type, contact_value).
  const existingContact = await db.customer_contacts.findUnique({
    where: {
      business_id_contact_type_contact_value: {
        business_id: input.businessId,
        contact_type: input.contactType,
        contact_value: normalizedValue,
      },
    },
    include: { customers: true },
  });

  if (!existingContact) {
    // ── New customer path ─────────────────────────────────────
    const now = new Date();
    const matterKey = `inbound:${now.getTime()}:${Math.random().toString(36).slice(2, 8)}`;

    const { cust, conv } = await db.$transaction(async (tx) => {
      const cust = await tx.customers.create({
        data: {
          business_id: input.businessId,
          display_name: displayName,
          first_contact_channel: input.channel,
          first_contact_at: now,
          consent_status: "implied_inbound",
          do_not_contact: false,
        },
      });
      await tx.customer_contacts.create({
        data: {
          customer_id: cust.id,
          business_id: input.businessId,
          contact_type: input.contactType,
          contact_value: normalizedValue,
          is_primary: true,
        },
      });
      const conv = await tx.conversations.create({
        data: {
          business_id: input.businessId,
          customer_id: cust.id,
          matter_key: matterKey,
          primary_state: "new_lead",
          current_owner: "ai",
          channel: input.channel,
          contact_handle: normalizedValue,
          contact_display_name: displayName,
        },
      });
      return { cust, conv };
    });

    return {
      customer: {
        id: cust.id,
        businessId: cust.business_id,
        displayName: cust.display_name,
        consentStatus: cust.consent_status as ConsentStatus,
        doNotContact: cust.do_not_contact,
        aiDisclosureSentAt: cust.ai_disclosure_sent_at,
        isNew: true,
        createdAt: cust.created_at,
      },
      conversation: {
        id: conv.id,
        businessId: conv.business_id,
        customerId: conv.customer_id,
        matterKey: conv.matter_key,
        primaryState: conv.primary_state as string,
        currentOwner: conv.current_owner,
        channel: conv.channel,
        contactHandle: conv.contact_handle,
        contactDisplayName: conv.contact_display_name,
        isReopened: false,
        createdAt: conv.created_at,
      },
    };
  }

  // ── Existing customer path ────────────────────────────────
  const customer = existingContact.customers;

  const customerResolved: CustomerResolved = {
    id: customer.id,
    businessId: customer.business_id,
    displayName: customer.display_name,
    consentStatus: customer.consent_status as ConsentStatus,
    doNotContact: customer.do_not_contact,
    aiDisclosureSentAt: customer.ai_disclosure_sent_at,
    isNew: false,
    createdAt: customer.created_at,
  };

  if (customer.do_not_contact) {
    return { customer: customerResolved, conversation: null };
  }

  // Find active (non-closed, non-archived) conversation.
  const activeConv = await db.conversations.findFirst({
    where: {
      business_id: input.businessId,
      customer_id: customer.id,
      is_archived: false,
      primary_state: { notIn: CLOSED_STATES as any },
    },
    orderBy: { updated_at: "desc" },
  });

  if (activeConv) {
    return {
      customer: customerResolved,
      conversation: {
        id: activeConv.id,
        businessId: activeConv.business_id,
        customerId: activeConv.customer_id,
        matterKey: activeConv.matter_key,
        primaryState: activeConv.primary_state as string,
        currentOwner: activeConv.current_owner,
        channel: activeConv.channel,
        contactHandle: activeConv.contact_handle,
        contactDisplayName: activeConv.contact_display_name,
        isReopened: false,
        createdAt: activeConv.created_at,
      },
    };
  }

  // Get auto_close_days for re-open window check.
  const biz = await db.businesses.findUnique({
    where: { id: input.businessId },
    select: { auto_close_days: true },
  });
  const autoCloseDays = biz?.auto_close_days ?? DEFAULT_AUTO_CLOSE_DAYS;

  // Find most recently closed (non-archived) conversation.
  const closedConv = await db.conversations.findFirst({
    where: {
      business_id: input.businessId,
      customer_id: customer.id,
      is_archived: false,
      primary_state: { in: CLOSED_STATES as any },
    },
    orderBy: { closed_at: "desc" },
  });

  if (closedConv) {
    const withinWindow = _isWithinReopenWindow(closedConv.closed_at, autoCloseDays);
    const now = new Date();
    const matterKey = `inbound:${now.getTime()}:${Math.random().toString(36).slice(2, 8)}`;

    const newConv = await db.$transaction(async (tx) => {
      const conv = await tx.conversations.create({
        data: {
          business_id: input.businessId,
          customer_id: customer.id,
          matter_key: matterKey,
          primary_state: "new_lead",
          current_owner: "ai",
          channel: input.channel,
          contact_handle: normalizedValue,
          contact_display_name: displayName,
        },
      });
      await tx.conversation_tags.create({
        data: {
          conversation_id: conv.id,
          business_id: input.businessId,
          tag_code: "repeat_customer",
          tag_source: "system",
          is_active: true,
        },
      });
      return conv;
    });

    return {
      customer: customerResolved,
      conversation: {
        id: newConv.id,
        businessId: newConv.business_id,
        customerId: newConv.customer_id,
        matterKey: newConv.matter_key,
        primaryState: newConv.primary_state as string,
        currentOwner: newConv.current_owner,
        channel: newConv.channel,
        contactHandle: newConv.contact_handle,
        contactDisplayName: newConv.contact_display_name,
        isReopened: withinWindow,
        createdAt: newConv.created_at,
      },
    };
  }

  // Existing customer, no prior conversations — create a fresh one.
  const now = new Date();
  const matterKey = `inbound:${now.getTime()}:${Math.random().toString(36).slice(2, 8)}`;
  const freshConv = await db.conversations.create({
    data: {
      business_id: input.businessId,
      customer_id: customer.id,
      matter_key: matterKey,
      primary_state: "new_lead",
      current_owner: "ai",
      channel: input.channel,
      contact_handle: normalizedValue,
      contact_display_name: displayName,
    },
  });

  return {
    customer: customerResolved,
    conversation: {
      id: freshConv.id,
      businessId: freshConv.business_id,
      customerId: freshConv.customer_id,
      matterKey: freshConv.matter_key,
      primaryState: freshConv.primary_state as string,
      currentOwner: freshConv.current_owner,
      channel: freshConv.channel,
      contactHandle: freshConv.contact_handle,
      contactDisplayName: freshConv.contact_display_name,
      isReopened: false,
      createdAt: freshConv.created_at,
    },
  };
}

// ── Test-only exports ─────────────────────────────────────────
// Never call these in production paths.

/** Clear all in-memory state. Call in beforeEach for test isolation. */
export function _resetStoreForTest(): void {
  _customers.clear();
  _contacts.clear();
  _conversations.clear();
  _tags.clear();
  _businesses.clear();
  _contactIndex.clear();
}

/**
 * Mark a conversation as closed (simulates auto-close or a state-machine
 * transition to a closed state). Used to set up E-category test scenarios.
 * Sets closedAt = now so the conversation is always within any auto-close window.
 */
export function _closeConversationForTest(conversationId: string): void {
  const conv = _conversations.get(conversationId);
  if (conv) {
    conv.primaryState = "closed_completed";
    conv.closedAt = new Date();
    conv.updatedAt = new Date();
  }
}

/** Mark a customer as do_not_contact. Used for F-category tests. */
export function _setDoNotContactForTest(customerId: string): void {
  const customer = _customers.get(customerId);
  if (customer) {
    customer.doNotContact = true;
    customer.updatedAt = new Date();
  }
}

/**
 * Return all tags for a conversation as plain objects.
 * Used by E06 to assert the repeat_customer tag was added.
 */
export function _getTagsForTest(
  conversationId: string,
): Array<{ tagCode: string; isActive: boolean }> {
  const result: Array<{ tagCode: string; isActive: boolean }> = [];
  for (const tag of _tags.values()) {
    if (tag.conversationId === conversationId) {
      result.push({ tagCode: tag.tagCode, isActive: tag.isActive });
    }
  }
  return result;
}

/**
 * Seed a business record with a custom auto_close_days value.
 * Defaults to 30 when not seeded — call this only when tests need
 * to verify the timing boundary behaviour.
 */
export function _seedBusinessAutoCloseDaysForTest(
  businessId: string,
  autoCloseDays: number,
): void {
  _businesses.set(businessId, { id: businessId, autoCloseDays });
}

/**
 * Backdate a conversation's closedAt to `daysAgo` days before now.
 * Use after _closeConversationForTest to place the close time outside
 * the auto_close_days window for E07/E08 scenarios.
 */
export function _setClosedAtForTest(conversationId: string, daysAgo: number): void {
  const conv = _conversations.get(conversationId);
  if (conv) {
    conv.closedAt = new Date(Date.now() - daysAgo * MS_PER_DAY);
  }
}

/**
 * Return the current primaryState of a conversation.
 * Used to assert that the old closed conversation was not mutated
 * during a re-open resolve call.
 */
export function _getConversationStateForTest(
  conversationId: string,
): { primaryState: string } | null {
  const conv = _conversations.get(conversationId);
  if (!conv) return null;
  return { primaryState: conv.primaryState };
}
